### ISSUE TITLE
Changing directories after connecting to sftp server

### ISSUE THREAD

**Issue by CraigThiebaud** [BriteVerify/node-sftp-server#12]
I've written my code so that ls works properly from a terminal window when I connect to my sftp server, but if I try and change directory with cd I get "Can't change directory: can't change target". Anyone have a solution for this?

**Comment by uberbrady** [comment]
I don't remember what 'cd' translate to; I *think* it's just going to try and `stat` the directory, then hold on to the path?

I think you should trace some of the `realpath` events and maybe the `stat` events too; and see if you can figure out what it's doing.

The last time I played with it, my code was actually dependent upon being able to change directories, and it *did* work - so I think the code should allow it.

Let me know what those events look like and I might be able to give you some pointers in the right direction.

**Comment by CraigThiebaud** [comment]
Hey so I partially figured out my problem,  setting up Stat appears to be the right way to go. However I've noticed that the statresponder passed as an argument into Stat isn't behaving as expected. None of the callbacks work with it, and upon outputting statresponder to the logs I don't see any of the error callbacks. Also returning the status using statresponder doesn't work, and says responder is an object not a function.

**Comment by uberbrady** [comment]
Re-reading the code, it looks like the 'stat' call is emitted like this:

```js
      return this.emit("stat", path, kind, new Statter(this.sftpStream, reqid));
```
The 'kind' is either `LSTAT` or `STAT` - the difference between the two only matters if you are trying to support symlinks, which we don't do yet.

The Statter object is defined around like 159 of the main `node-sft-server.js` file. I think it wants you to call things like:

```js
mystatter.is_file(); //to indicate the thing you're statting is a file
// you could also do .is_directory() to indicate a directory.
mystatter.permissions=0777; //unix-style permissions number
mystatter.uid=1234; //unix-style user ID for owner
mystatter.gid=1234; //unix-style Group ID 
mystatter.size=555; //file size in bytes
mystatter.atime=123456789; //unix-style second-from-epoch
mystatter.mtime=123456789; //same
mystatter.file(); //to actually return the stat block; this completes the 'stat()' call.

//and if a file is nonexistent, you can do:
mystatter.nofile();
```

That interface is not very good, but I should at least document it properly. I will also probably want to refactor it - the timestamps should be Javascript datetimes, etc, etc.

If this works for you, could you put together a quick pull request fixing the documentation? I'll make sure to accept it quickly.

**Comment by blargity** [comment]
I was having this same issue, so I just opened a PR with some documentation on this, and I removed the `attrs` parameter from `file()` as it was getting ignored anyway.

**Comment by uberbrady** [comment]
Thanks, @blargity - I've merged that in; looks great!
