### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by bchr02** [BriteVerify/node-sftp-server#22]
Just curious if node-sftp-server works on Windows? Thanks.

**Comment by uberbrady** [comment]
The answer so far is...maybe. We've had a few Windows users who have had some problems with the fundamentals in the past, and I don't know of any Windows users who are using it succesfully (though, even if they are, they certainly don't have to tell us about it).

I'd say give it a try and we can see what happens. If it doesn't work, I'd like to fix it so it stays totally cross-platform (if I can do that without junking up the code too badly).

**Comment by bchr02** [comment]
Okay thank you. At this point I am trying to use another none node solution. If I need to revert to trying this module I will post my results.

**Comment by davidAtBar** [comment]
@bchr02 did you happen to find a good node sftp solution?

**Comment by bchr02** [comment]
I ended up forcing my vendor to support FTPS instead. And for that I used IIS.
