### ISSUE TITLE
get remote IP?

### ISSUE THREAD

**Issue by mashpie** [BriteVerify/node-sftp-server#29]
Hi there,

is there any chance to get the client's IP connecting to that server? 
Tried to find some info by tracking `auth` and `session`.

Any hints?

Thanks,
Marcus

**Comment by uberbrady** [comment]
Hrm, well, it's gotta be in there _somewhere_, I'm sure. The library we're wrapping for this project is https://github.com/mscdex/ssh2-streams - and they have documentation on the SFTPStream part here at https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md

Hopefully, it's in there somewhere. If so, and we don't expose it properly, let us know and we'll make a change.

It totally makes sense that we should expose the connecting client's IP address to the authentication process as well as the early connection process, I just don't off the top of my head know exactly where that would be...

**Comment by uberbrady** [comment]
in 0.3.0, the connect event handler now takes a second parameter which includes IP address.
