### ISSUE TITLE
DirectoryEmitter 'dir' event calls listener with undefined, not responder object

### ISSUE THREAD

**Issue by leontastic** [BriteVerify/node-sftp-server#47]
From the README:

> `.on("readdir",function (path,directory_emitter) { })` - on a directory listing attempt, the directory_emitter will keep emitting dir messages with a responder as a parameter, allowing you to respond with responder.file(filename, attrs) to return a file entry in the directory, or responder.end() if the directory listing is complete.

I tried this out, the `directory_emitter` argument does indeed emit a `dir` event, but it passes `undefined` into the callback. Hence calling `directory_emitter.file(name, attrs)` will error with `TypeError: Cannot read property 'file' of undefined`.

Is the documentation wrong, or is there a bug in the code? If the documentation is not accurate, what is the correct usage so that I can send file information down the wire in response to a `readdir` SFTP request?

**Comment by uberbrady** [comment]
Well, if the documentation threw you, then it's buggy, and we should fix it. Would you be willing to help?

so the thing you should be calling `.file()` on is not the parameter to the `dir` event, but the `directory_emitter` in the documentation.

Our server example looks like this (it just creates directories named 1,2,3,4,....9999):

```js
    session.on("readdir", function(path, responder) {
      var dirs, i, j, results;
      console.warn("Readdir request for path: " + path);
      dirs = (function() {
        results = [];
        for (j = 1; j < 10000; j++){ results.push(j); }
        return results;
      }).apply(this);
      i = 0;
      responder.on("dir", function() {
        if (dirs[i]) {
          console.warn("Returning directory: " + dirs[i]);
          responder.file(dirs[i]);
          return i++;
        } else {
          return responder.end();
        }
      });
      return responder.on("end", function() {
        return console.warn("Now I would normally do, like, cleanup stuff, for this directory listing");
      });
    });
```

**Comment by leontastic** [comment]
@uberbrady I realized that after checking the example server too – it works with the usage you've described. I can put in a PR to update the docs with the correct usage and an example too, so future users don't get thrown by the docs. Thanks!

**Comment by leontastic** [comment]
@uberbrady Here's the PR: #48
